### Site info:
title: idahogbakk
tagline: "@idahogbakk reiser og oppdager verden og lærer nye ting underveis."
author: Ida Kristine Høgbakk
email: ida.kristine@hogbakk.no
description: "" # You can edit this line in _config.yml. It will appear in your document head meta and in your feed.xml site description
keywords: 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://idahogbakk.no" # the base hostname & protocol for your site
locale: "no_NB"

### Personal info and site tools info:
twitter_username: idahogbakk
github_username:  idahogbakk
disqus_shortname:
favicon:
aboutme:
aboutme_photo:
google_analytics_key: "UA-6412130-5" # put YOUR key here to enable tracking! (blank to disable)


### Site setting:
ShowContactInfo: "False" # Personal Info (twitter,github,email) can be seen on aboutme-sidebar, those info only shown where ShowContactInfo == True
default_column: "two" # blog style: two columns, if default_column != "two", you will see a one column blog.
default_locale: "en"
permalink: "/:year/:month/:day/:title/"

locales:
    en:
      Aboutme: "Om meg"
      Archives: "Arkiv"
      Blogroll: "Blogroll"
      Categories: "Kategorier"
      Copyright_Notice: "Copyright Notice"
      Recent_Posts: "Siste innlegg"
      Tags: "Emneord"
      Previous: "Eldre"
      Next: "Nyere"
      PostedInCategories: "Dette innlegget ble skrevet i"
      Taggedwith: "og merket"
      PostDate: ""
      Google_search: "Søk"
      Home: "Hjem"
      About: "Om"
      Guestbook: "Gjestebok"
      Subscribe: "Abonner"

### Build settings
markdown: kramdown
#highlighter: pygments
kramdown:
        input: GFM
        syntax_highlighter: rouge

plugins: [jekyll-paginate]
paginate: 5
excerpt_separator: <!--more-->
